apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        image: ghcr.io/mlflow/mlflow:v3.12.0-full
        command: ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000"]
        env:
        - name: MLFLOW_DISABLE_SECURITY
          value: "true"
        ports:
        - containerPort: 5000
        env:
        - name: MLFLOW_BACKEND_STORE_URI
          value: "postgresql://mlflow_user:groskiki@postgres-service:5432/mlflow_db"
        - name: MLFLOW_DEFAULT_ARTIFACT_ROOT
          value: "/mlflow/artifacts"
        volumeMounts:
        - name: artifacts-storage
          mountPath: /mlflow/artifacts
      volumes:
      - name: artifacts-storage
        persistentVolumeClaim:
          claimName: artifacts-pvc